# -*- coding: utf-8 -*-
# -------------------------------------------------------------------------------
# Name:         detect.py
# Description:  This script is used to detect the poetry generated by GPT-2 model.
# Author:       shaver
# Date:         2025/5/12
# -------------------------------------------------------------------------------

from transformers import AutoModelForCausalLM,AutoTokenizer,TextGenerationPipeline
import torch

model_path = r"/root/autodl-tmp/model/gpt-chinese/models--uer--gpt2-chinese-cluecorpussmall/snapshots/c2c0249d8a2731f269414cc3b22dff021f8e07a3"  # 预训练模型路径

tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForCausalLM.from_pretrained(model_path)

#加载我们自己训练的权重（中文古诗词）
model.load_state_dict(torch.load("params/net.pt"))

#使用系统自带的pipeline工具生成内容
pipeline = TextGenerationPipeline(model,tokenizer,device=0)

print(pipeline("安子",max_length =24))